services:
  postgres:
    image: postgres:16
    container_name: todo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: todolistdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
